{
 "title": "Dashboard 1",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance" }
  ]
 },
 "panels": [
  {
   "title": "Disk Read Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "InstanceId": "$Instance" },
     "metricName": "DiskReadOps",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Disk Write Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": { "InstanceId": "$Instance" },
     "metricName": "DiskWriteOps",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dimensions": { "InstanceId": "$Instance" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dimensions": { "InstanceId": "$Instance" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Network Packets Incoming",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}